name: flutter_clean_lint
description: "Custom lints for Flutter"
version: 1.0.0

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  analysis_server_plugin: 0.3.8
  analyzer: 10.0.2

dev_dependencies:
  analyzer_testing: 0.1.10
  test: ^1.25.0
  test_reflective_loader: ^0.4.0
  lints: ^6.0.0
